name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  go-version: "1.16"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.go-version }}
    - name: Build
      run: |
        bash build.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: webrcon-server
        path: ./output/webrcon-server
