name: Create Release

on:
  push:
    tags:
      - 'v*'

env:
  go-version: "1.16"

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}
      - name: Build
        run: |
          bash build.sh all
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            output/*.tar.gz
            output/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
